### ISSUE TITLE
'Sphere' object has no attribute 'intersectsSphere'

### ISSUE THREAD

**Issue by dronov-dmitry** [stemkoski/three.py#15]
When i run TestCollisionDetection.py
It wright me:
'Sphere' object has no attribute 'intersectsSphere'

Full error text is : 

`Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "c:/Users/Admin/Documents/MEGAsync/06_All/14_JS/02_PythonJS/three.py-master/three.py-master/three.py/TestCollisionDetection.py", line 95, in <module>
    TestCollisionDetection().run()
  File "c:\Users\Admin\Documents\MEGAsync\06_All\14_JS\02_PythonJS\three.py-master\three.py-master\three.py\core\Base.py", line 76, in run
    self.update()
  File "c:/Users/Admin/Documents/MEGAsync/06_All/14_JS/02_PythonJS/three.py-master/three.py-master/three.py/TestCollisionDetection.py", line 71, in update
    if mesh.overlaps(self.Mesh1):
  File "c:\Users\Admin\Documents\MEGAsync\06_All\14_JS\02_PythonJS\three.py-master\three.py-master\three.py\physics\ComponentMesh.py", line 20, in overlaps
    overlaps = (self.componentDict["Sphere"].intersectsSphere(other.componentDict["Sphere"]))        
AttributeError: 'Sphere' object has no attribute 'intersectsSphere'`

**Comment by AlexisTercero55** [comment]
It seems just a misspelled attribute, it was fixed by replace `.intersectsSphere` for `.intersectSphere` at `./physics/ComponentMesh.py:20:50`. I've request for merge the changes. After changes it runs well:

![issue-threepy](https://user-images.githubusercontent.com/87354316/213340880-a583c787-266c-4fac-9aaa-404d07fe7df8.png)

Kind regards! :3
